version: "3"
services:
  server:
    build: src/Server
    command:  java Server.java
    ports:
      - "5000:5000"
  client:
    build: src/Client
    command:  java Client.java
    network_mode: host
    depends_on:
      server:
        condition: service_started